ktor:
  application:
    modules:
      - app.palone.ApplicationKt.module
  deployment:
    port: 3000
    host: 192.168.0.45
postgres:
  url: "YourPostreSQLURL"
  user: avnadmin
  password: YourPassword
